const manageExeatData = [
  {
    id: 1,
    name: "John Doe",
    time: "8:30 AM",
    avatar: "src/assets/avatar/avatar1.webp",
    vehicle_number: "AS 1234 - 23",
    accomp_staff: "Derrick Johnson",
    destination: "Airport",
    purpose: "Airport Pickup",
  },
  {
    id: 2,
    name: "Jane Smith",
    time: "9:00 AM",
    avatar: "src/assets/avatar/avatar2.jpg",
    vehicle_number: "AS 5678 - 24",
    accomp_staff: "Sarah Davis",
    destination: "City Center",
    purpose: "Client Meeting",
  },
  {
    id: 3,
    name: "Bob Williams",
    time: "10:00 AM",
    avatar: "src/assets/avatar/avatar4.jpg",
    vehicle_number: "AS 9012 - 22",
    accomp_staff: "Michael Brown",
    destination: "Shopping Mall",
    purpose: "Grocery Shopping",
  },
  {
    id: 4,
    name: "John Doe",
    avatar: "src/assets/avatar/avatar1.webp",
    time: "11:30 AM",
    vehicle_number: "AS 3456 - 21",
    accomp_staff: "Emily Davis",
    destination: "Restaurant",
    purpose: "Lunch Break",
  },
  {
    id: 5,
    name: "Jane Smith",
    time: "12:00 PM",
    avatar: "src/assets/avatar/avatar2.jpg",
    vehicle_number: "AS 7890 - 25",
    accomp_staff: "Robert Wilson",
    destination: "Client Site",
    purpose: "Business Visit",
  },
  {
    id: 6,
    name: "Alice Johnson",
    avatar: "src/assets/avatar/avatar3.avif",
    time: "1:30 PM",
    vehicle_number: "AS 2345 - 22",
    accomp_staff: "Olivia Davis",
    destination: "Hospital",
    purpose: "Medical Checkup",
  },
  {
    id: 7,
    name: "Bob Williams",
    time: "2:00 PM",
    avatar: "src/assets/avatar/avatar4.jpg",
    vehicle_number: "AS 6789 - 24",
    accomp_staff: "Sophia Wilson",
    destination: "School",
    purpose: "Student Drop-off",
  },
  {
    id: 8,
    name: "Emily Brown",
    time: "3:30 PM",
    avatar: "src/assets/avatar/avatar5.svg",
    vehicle_number: "AS 1234 - 23",
    accomp_staff: "Godfrey Johnson",
    destination: "Gym",
    purpose: "Workout Session",
  },
];

export default manageExeatData;
